service:
  name: finance

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-2
  stage: dev

functions:
  test:
    handler: src/router/syncCorpList.main
    events:
      - http:
          method: get
          path: corp-list
